theme: jekyll-theme-minimal
title: Xedule Import
description: Xedule Import is een hulpmiddel gemaakt om het rooster uit Xedule te bewerken alvorens het wordt geimporteerd in Outlook. Door een paar wijzigingen door te voeren aan het door Xedule geexporteerde .ics bestand wordt het sneller en makkelijker om je rooster toe te voegen aan Outlook en later ook weer te verwijderen.

Dit hulpmiddel is onstaan omdat er geen standaard tools zijn om je rooster goed in je agenda te krijgen. Tot die tools er zijn heb je Xedule Import.
